### PR TITLE
Fix clang-cl build with Visual Studio

### LINKED ISSUE #763: Support clang under Visual Studio
A separate ticket as per @jkeiser's request 

On Windows 10 64bit, with:
- MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.26)
- Windows 10 SDK (10.0.18362.0)
- Clang 10.0.0

In a folder named check, I put `simdjson.h`, `simdjson.cpp` and `check.cpp`:

```
#include "simdjson.h"

int main () {

    // simdjson::dom::parser parser;
    // simdjson::dom::element doc = parser.parse("[1,2,3]"_padded);

}
```

Then, from the folder in the command line, I run:

` clang++ -std=c++17 -o check.exe check.cpp simdjson.cpp`

I get:
```
simdjson.cpp:2411:20: error: use of undeclared identifier '_mm_clmulepi64_si128'
  __m128i result = _mm_clmulepi64_si128(_mm_set_epi64x(0ULL, bitmask), all_ones, 0);
                   ^
simdjson.cpp:2457:10: error: use of undeclared identifier '_blsr_u64'
  return _blsr_u64(input_num);
         ^
simdjson.cpp:2462:27: error: use of undeclared identifier '_lzcnt_u64'; did you mean '__tzcnt_u64'?
  return static_cast<int>(_lzcnt_u64(input_num));
                          ^~~~~~~~~~
                          __tzcnt_u64
C:\Program Files\LLVM\lib\clang\10.0.0\include\bmiintrin.h:87:1: note: '__tzcnt_u64' declared here
__tzcnt_u64(unsigned long long __X)
^
simdjson.cpp:2516:5: error: unknown type name '__m256i'
    __m256i value;
    ^
simdjson.cpp:2522:30: error: unknown type name '__m256i'
    really_inline base(const __m256i _value) : value(_value) {}
                             ^
simdjson.cpp:2525:34: error: unknown type name '__m256i'
    really_inline operator const __m256i&() const { return this->value; }
                                 ^
simdjson.cpp:2548:31: error: unknown type name '__m256i'
    really_inline base8(const __m256i _value) : base<simd8<T>>(_value) {}
                              ^
simdjson.cpp:2566:37: error: unknown type name '__m256i'
    really_inline simd8<bool>(const __m256i _value) : base8<bool>(_value) {}
                                    ^
simdjson.cpp:2563:66: error: use of undeclared identifier '_mm256_set1_epi8'; did you mean '_mm_set1_epi8'?
    static really_inline simd8<bool> splat(bool _value) { return _mm256_set1_epi8(-(!!_value)); }
                                                                 ^~~~~~~~~~~~~~~~
                                                                 _mm_set1_epi8
C:\Program Files\LLVM\lib\clang\10.0.0\include\emmintrin.h:3842:1: note: '_mm_set1_epi8' declared here
_mm_set1_epi8(char __b)
^
simdjson.cpp:2563:66: error: no viable conversion from returned value of type '__m128i' (vector of 2 'long long' values) to function return type 'simd8<bool>'
    static really_inline simd8<bool> splat(bool _value) { return _mm256_set1_epi8(-(!!_value)); }
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
simdjson.cpp:2562:10: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from '__m128i' (vector of 2 'long long' values) to 'const simdjson::haswell::simd::simd8<bool> &' for 1st argument
  struct simd8<bool>: base8<bool> {
         ^
simdjson.cpp:2562:10: note: candidate constructor (the implicit move constructor) not viable: no known conversion from '__m128i' (vector of 2 'long long' values) to 'simdjson::haswell::simd::simd8<bool> &&' for 1st argument
  struct simd8<bool>: base8<bool> {
         ^
simdjson.cpp:2568:19: note: candidate constructor not viable: no known conversion from '__m128i' (vector of 2 'long long' values) to 'bool' for 1st argument
    really_inline simd8<bool>(bool _value) : base8<bool>(splat(_value)) {}
                  ^
simdjson.cpp:2565:35: error: member initializer 'base8' does not name a non-static data member or base class
    really_inline simd8<bool>() : base8() {}
                                  ^~~~~~~
simdjson.cpp:2568:46: error: type 'base8<bool>' is not a direct or virtual base of 'simdjson::haswell::simd::simd8<bool>'
    really_inline simd8<bool>(bool _value) : base8<bool>(splat(_value)) {}
                                             ^~~~~~~~~~~
simdjson.cpp:2570:51: error: use of undeclared identifier '_mm256_movemask_epi8'; did you mean '_mm_movemask_epi8'?
    really_inline int to_bitmask() const { return _mm256_movemask_epi8(*this); }
                                                  ^~~~~~~~~~~~~~~~~~~~
                                                  _mm_movemask_epi8
C:\Program Files\LLVM\lib\clang\10.0.0\include\emmintrin.h:4399:1: note: '_mm_movemask_epi8' declared here
_mm_movemask_epi8(__m128i __a)
^
simdjson.cpp:2570:72: error: no viable conversion from 'const simdjson::haswell::simd::simd8<bool>' to '__m128i' (vector of 2 'long long' values)
    really_inline int to_bitmask() const { return _mm256_movemask_epi8(*this); }
                                                                       ^~~~~
C:\Program Files\LLVM\lib\clang\10.0.0\include\emmintrin.h:4399:27: note: passing argument to parameter '__a' here
_mm_movemask_epi8(__m128i __a)
                          ^
simdjson.cpp:2571:46: error: use of undeclared identifier '_mm256_testz_si256'
    really_inline bool any() const { return !_mm256_testz_si256(*this, *this); }
                                             ^
simdjson.cpp:2572:64: error: invalid operands to binary expression ('const simdjson::haswell::simd::simd8<bool>' and 'bool')
    really_inline simd8<bool> operator~() const { return *this ^ true; }
                                                         ~~~~~ ^ ~~~~
simdjson.cpp:2596:39: error: unknown type name '__m256i'
    really_inline base8_numeric(const __m256i _value) : base8<T>(_value) {}
                                      ^
simdjson.cpp:2685:31: error: unknown type name '__m256i'
    really_inline simd8(const __m256i _value) : base8_numeric<int8_t>(_value) {}
                              ^
simdjson.cpp:2684:29: error: type 'base8_numeric<int8_t>' (aka 'base8_numeric<signed char>') is not a direct or virtual base of 'simdjson::haswell::simd::simd8<int8_t>'
    really_inline simd8() : base8_numeric<int8_t>() {}
                            ^~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

### PR DESCRIPTION
**Pull request by pps83**
fixes #763

### CODE REVIEW

**Comment by pps83** [comment]
Note, that `/arch:AVX2` is required for clang-cl. Whoever uses it with clang will have to add that to compiler flags:

image

**Comment by lemire** [comment]
> Note, that /arch:AVX2 is required for clang-cl. Whoever uses it with clang will have to add that to compiler flags:

No. This destroys runtime dispatch.

When you set  /arch:AVX2, you allow the compiler to use AVX2 whenever it wants so the result won't be portable.

Thus this function

```C++
int f(int * x) {
    int a = 0;
    for(int z = 0; z < 1024; z++) a += x[z];
    return a;
}
```

compiles to

```asm
int f(int *) PROC                                  ; f, COMDAT
        vpxor   xmm1, xmm1, xmm1
        vpxor   xmm2, xmm2, xmm2
        xor     eax, eax
        npad    6
$LL4@f:
        vpaddd  ymm1, ymm1, YMMWORD PTR [rcx+rax*4]
        vpaddd  ymm2, ymm2, YMMWORD PTR [rcx+rax*4+32]
        add     rax, 16
        cmp     rax, 1024               ; 00000400H
        jl      SHORT $LL4@f
        vpaddd  ymm0, ymm2, ymm1
        vphaddd ymm1, ymm0, ymm0
        vphaddd ymm2, ymm1, ymm1
        vextracti128 xmm0, ymm2, 1
        vpaddd  xmm0, xmm2, xmm0
        vmovd   eax, xmm0
        vzeroupper
        ret     0
```

Notice the use of ymm* registers? Those require AVX/AVX2.

**Comment by pps83** [comment]
This isn't part of this PR, but clang will not compiler code without this flag.

File: src/haswell/intrinsics.h [hunk 1]
```diff
@@ -4,7 +4,14 @@
 #include "simdjson.h"
 
 #ifdef _MSC_VER
-#include <intrin.h> // visual studio
+// visual studio (or clang-cl)
+#include <intrin.h>
```
Comment (lemire) [inline src/haswell/intrinsics.h:8]: intrin.h will include the other headers

```
#include <bmiintrin.h>
 #include <lzcntintrin.h>
 #include <immintrin.h>
 #include <wmmintrin.h>
```

so this does preprocessor branch probably does nothing.

Comment (pps83) [reply src/haswell/intrinsics.h:8]: I didn't add it cause I was bored. clang-cl needs it.

File: include/simdjson/common_defs.h [hunk 2]
```diff
@@ -119,7 +119,15 @@ constexpr size_t DEFAULT_MAX_DEPTH = 1024;
   #define SIMDJSON_DISABLE_DEPRECATED_WARNING SIMDJSON_DISABLE_GCC_WARNING(-Wdeprecated-declarations)
   #define SIMDJSON_POP_DISABLE_WARNINGS _Pragma("GCC diagnostic pop")
 
-  #define SIMDJSON_DLLIMPORTEXPORT
+  #if defined(_MSC_VER) && defined(__clang__)
```
Comment (lemire) [inline include/simdjson/common_defs.h:122]: This is good.

Comment (pps83) [reply include/simdjson/common_defs.h:122]: by the way, gcc supposed dllimport/dllexport. Perhaps it should always be used. `SIMDJSON_DLLIMPORTEXPORT` should be renamed to `SIMDJSON_API`. But that's all for another change

Comment (lemire) [reply include/simdjson/common_defs.h:122]: Yes, make it a distinct issue, please.

**Comment by lemire** [comment]
So the original issue here is to support clang 10 under Visual Studio (you can download clang 10  at https://releases.llvm.org/download.html#10.0.0). Here is the result that I get with this PR:

```
PS C:\Users\User\Documents\GitHub\simdjsonpps83\singleheader> clang  -o test.exe .\amalgamate_demo.cpp
In file included from .\amalgamate_demo.cpp:4:
./simdjson.h:4910:24: warning: 'fopen' is deprecated: This function or variable may be
      unsafe. Consider using fopen_s instead. To disable deprecation, use
      _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations] 
  std::FILE *fp = std::fopen(path.c_str(), "rb");
                       ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h:207:20: note:  
      'fopen' has been explicitly marked deprecated here
    _Check_return_ _CRT_INSECURE_DEPRECATE(fopen_s)
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:316:55: note: 
      expanded from macro '_CRT_INSECURE_DEPRECATE'
        #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
                                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:306:47: note: 
      expanded from macro '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
In file included from .\amalgamate_demo.cpp:4:
./simdjson.h:6277:24: warning: 'fopen' is deprecated: This function or variable may be  
      unsafe. Consider using fopen_s instead. To disable deprecation, use
      _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations] 
  std::FILE *fp = std::fopen(filename.c_str(), "rb");
                       ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h:207:20: note:  
      'fopen' has been explicitly marked deprecated here
    _Check_return_ _CRT_INSECURE_DEPRECATE(fopen_s)
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:316:55: note: 
      expanded from macro '_CRT_INSECURE_DEPRECATE'
        #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
                                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:306:47: note: 
      expanded from macro '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:564:37: warning: 'getenv' is deprecated: This function or variable may be
      unsafe. Consider using _dupenv_s instead. To disable deprecation, use
      _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations] 
  char *force_implementation_name = getenv("SIMDJSON_FORCE_IMPLEMENTATION");
                                    ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdlib.h:1190:20: note:
      'getenv' has been explicitly marked deprecated here
    _Check_return_ _CRT_INSECURE_DEPRECATE(_dupenv_s)
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:316:55: note: 
      expanded from macro '_CRT_INSECURE_DEPRECATE'
        #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
                                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:306:47: note: 
      expanded from macro '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:2417:20: error: use of undeclared identifier '_mm_clmulepi64_si128'      
  __m128i result = _mm_clmulepi64_si128(_mm_set_epi64x(0ULL, bitmask), all_ones, 0);    
                   ^
./simdjson.cpp:2463:10: error: use of undeclared identifier '_blsr_u64'
  return _blsr_u64(input_num);
         ^
./simdjson.cpp:2468:14: error: use of undeclared identifier '_lzcnt_u64'; did you mean
      '__tzcnt_u64'?
  return int(_lzcnt_u64(input_num));
             ^~~~~~~~~~
             __tzcnt_u64
C:\Program Files\LLVM\lib\clang\10.0.0\include\bmiintrin.h:87:1: note: '__tzcnt_u64'    
      declared here
__tzcnt_u64(unsigned long long __X)
^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:2524:5: error: unknown type name '__m256i'
    __m256i value;
    ^
./simdjson.cpp:2530:30: error: unknown type name '__m256i'
    really_inline base(const __m256i _value) : value(_value) {}
                             ^
./simdjson.cpp:2533:34: error: unknown type name '__m256i'
    really_inline operator const __m256i&() const { return this->value; }
                                 ^
./simdjson.cpp:2556:31: error: unknown type name '__m256i'
    really_inline base8(const __m256i _value) : base<simd8<T>>(_value) {}
                              ^
./simdjson.cpp:2574:37: error: unknown type name '__m256i'
    really_inline simd8<bool>(const __m256i _value) : base8<bool>(_value) {}
                                    ^
./simdjson.cpp:2571:66: error: use of undeclared identifier '_mm256_set1_epi8'; did you
      mean '_mm_set1_epi8'?
  ...really_inline simd8<bool> splat(bool _value) { return _mm256_set1_epi8(uint8_t(-...
                                                           ^~~~~~~~~~~~~~~~
                                                           _mm_set1_epi8
C:\Program Files\LLVM\lib\clang\10.0.0\include\emmintrin.h:3842:1: note: 
      '_mm_set1_epi8' declared here
_mm_set1_epi8(char __b)
^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:2571:66: error: no viable conversion from returned value of type
      '__m128i' (vector of 2 'long long' values) to function return type 'simd8<bool>'  
  ...splat(bool _value) { return _mm256_set1_epi8(uint8_t(-(!!_value))); }
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./simdjson.cpp:2570:10: note: candidate constructor (the implicit copy constructor) not 
      viable: no known conversion from '__m128i' (vector of 2 'long long' values) to    
      'const simdjson::haswell::simd::simd8<bool> &' for 1st argument
  struct simd8<bool>: base8<bool> {
         ^
./simdjson.cpp:2570:10: note: candidate constructor (the implicit move constructor) not
      viable: no known conversion from '__m128i' (vector of 2 'long long' values) to    
      'simdjson::haswell::simd::simd8<bool> &&' for 1st argument
  struct simd8<bool>: base8<bool> {
         ^
./simdjson.cpp:2576:19: note: candidate constructor not viable: no known conversion from
      '__m128i' (vector of 2 'long long' values) to 'bool' for 1st argument
    really_inline simd8<bool>(bool _value) : base8<bool>(splat(_value)) {}
                  ^
./simdjson.cpp:2573:35: error: member initializer 'base8' does not name a non-static
      data member or base class
    really_inline simd8<bool>() : base8() {}
                                  ^~~~~~~
./simdjson.cpp:2576:46: error: type 'base8<bool>' is not a direct or virtual base of
      'simdjson::haswell::simd::simd8<bool>'
    really_inline simd8<bool>(bool _value) : base8<bool>(splat(_value)) {}
                                             ^~~~~~~~~~~
./simdjson.cpp:2578:51: error: use of undeclared identifier '_mm256_movemask_epi8'; did
      you mean '_mm_movemask_epi8'?
    really_inline int to_bitmask() const { return _mm256_movemask_epi8(*this); }        
                                                  ^~~~~~~~~~~~~~~~~~~~
                                                  _mm_movemask_epi8
C:\Program Files\LLVM\lib\clang\10.0.0\include\emmintrin.h:4399:1: note: 
      '_mm_movemask_epi8' declared here
_mm_movemask_epi8(__m128i __a)
^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:2578:72: error: no viable conversion from 'const
      simdjson::haswell::simd::simd8<bool>' to '__m128i'
      (vector of 2 'long long' values)
    really_inline int to_bitmask() const { return _mm256_movemask_epi8(*this); }        
                                                                       ^~~~~
C:\Program Files\LLVM\lib\clang\10.0.0\include\emmintrin.h:4399:27: note: passing       
      argument to parameter '__a' here
_mm_movemask_epi8(__m128i __a)
                          ^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:2579:46: error: use of undeclared identifier '_mm256_testz_si256'
    really_inline bool any() const { return !_mm256_testz_si256(*this, *this); }        
                                             ^
      simdjson::haswell::simd::simd8<bool>' and 'bool')
    really_inline simd8<bool> operator~() const { return *this ^ true; }
                                                         ~~~~~ ^ ~~~~
./simdjson.cpp:2604:39: error: unknown type name '__m256i'
    really_inline base8_numeric(const __m256i _value) : base8<T>(_value) {}
                                      ^
./simdjson.cpp:2693:31: error: unknown type name '__m256i'
    really_inline simd8(const __m256i _value) : base8_numeric<int8_t>(_value) {}        
                              ^
./simdjson.cpp:2692:29: error: type 'base8_numeric<int8_t>' (aka 'base8_numeric<signed  
      char>') is not a direct or virtual base of
      'simdjson::haswell::simd::simd8<int8_t>'
    really_inline simd8() : base8_numeric<int8_t>() {}
                            ^~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.
PS C:\Users\User\Documents\GitHub\simdjsonpps83\singleheader> clang  -o test.exe .\amalgamate_demo.cpp
In file included from .\amalgamate_demo.cpp:4:
./simdjson.h:4910:24: warning: 'fopen' is deprecated: This function or variable may be
      unsafe. Consider using fopen_s instead. To disable deprecation, use
      _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations] 
  std::FILE *fp = std::fopen(path.c_str(), "rb");
                       ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h:207:20: note: 
      'fopen' has been explicitly marked deprecated here
    _Check_return_ _CRT_INSECURE_DEPRECATE(fopen_s)
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:316:55: note: 
      expanded from macro '_CRT_INSECURE_DEPRECATE'
        #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
                                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:306:47: note: 
      expanded from macro '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
In file included from .\amalgamate_demo.cpp:4:
./simdjson.h:6277:24: warning: 'fopen' is deprecated: This function or variable may be  
      unsafe. Consider using fopen_s instead. To disable deprecation, use
      _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations] 
  std::FILE *fp = std::fopen(filename.c_str(), "rb");
                       ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h:207:20: note:  
      'fopen' has been explicitly marked deprecated here
    _Check_return_ _CRT_INSECURE_DEPRECATE(fopen_s)
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:316:55: note: 
      expanded from macro '_CRT_INSECURE_DEPRECATE'
        #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
                                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:306:47: note: 
      expanded from macro '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:564:37: warning: 'getenv' is deprecated: This function or variable may be
      unsafe. Consider using _dupenv_s instead. To disable deprecation, use
      _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations] 
  char *force_implementation_name = getenv("SIMDJSON_FORCE_IMPLEMENTATION");
                                    ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdlib.h:1190:20: note:
      'getenv' has been explicitly marked deprecated here
    _Check_return_ _CRT_INSECURE_DEPRECATE(_dupenv_s)
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:316:55: note: 
      expanded from macro '_CRT_INSECURE_DEPRECATE'
        #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
                                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:306:47: note: 
      expanded from macro '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:2417:20: error: use of undeclared identifier '_mm_clmulepi64_si128'
  __m128i result = _mm_clmulepi64_si128(_mm_set_epi64x(0ULL, bitmask), all_ones, 0);    
                   ^
./simdjson.cpp:2463:10: error: use of undeclared identifier '_blsr_u64'
  return _blsr_u64(input_num);
         ^
./simdjson.cpp:2468:14: error: use of undeclared identifier '_lzcnt_u64'; did you mean
      '__tzcnt_u64'?
  return int(_lzcnt_u64(input_num));
             ^~~~~~~~~~
             __tzcnt_u64
C:\Program Files\LLVM\lib\clang\10.0.0\include\bmiintrin.h:87:1: note: '__tzcnt_u64'    
      declared here
__tzcnt_u64(unsigned long long __X)
^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:2524:5: error: unknown type name '__m256i'
    __m256i value;
    ^
./simdjson.cpp:2530:30: error: unknown type name '__m256i'
    really_inline base(const __m256i _value) : value(_value) {}
                             ^
./simdjson.cpp:2533:34: error: unknown type name '__m256i'
    really_inline operator const __m256i&() const { return this->value; }
                                 ^
./simdjson.cpp:2556:31: error: unknown type name '__m256i'
    really_inline base8(const __m256i _value) : base<simd8<T>>(_value) {}
                              ^
./simdjson.cpp:2574:37: error: unknown type name '__m256i'
    really_inline simd8<bool>(const __m256i _value) : base8<bool>(_value) {}
                                    ^
./simdjson.cpp:2571:66: error: use of undeclared identifier '_mm256_set1_epi8'; did you
      mean '_mm_set1_epi8'?
  ...really_inline simd8<bool> splat(bool _value) { return _mm256_set1_epi8(uint8_t(-...
                                                           ^~~~~~~~~~~~~~~~
                                                           _mm_set1_epi8
C:\Program Files\LLVM\lib\clang\10.0.0\include\emmintrin.h:3842:1: note: 
      '_mm_set1_epi8' declared here
_mm_set1_epi8(char __b)
^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:2571:66: error: no viable conversion from returned value of type
      '__m128i' (vector of 2 'long long' values) to function return type 'simd8<bool>'  
  ...splat(bool _value) { return _mm256_set1_epi8(uint8_t(-(!!_value))); }
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./simdjson.cpp:2570:10: note: candidate constructor (the implicit copy constructor) not 
      viable: no known conversion from '__m128i' (vector of 2 'long long' values) to
      'const simdjson::haswell::simd::simd8<bool> &' for 1st argument
  struct simd8<bool>: base8<bool> {
         ^
./simdjson.cpp:2570:10: note: candidate constructor (the implicit move constructor) not 
      viable: no known conversion from '__m128i' (vector of 2 'long long' values) to
      'simdjson::haswell::simd::simd8<bool> &&' for 1st argument
  struct simd8<bool>: base8<bool> {
         ^
./simdjson.cpp:2576:19: note: candidate constructor not viable: no known conversion from
      '__m128i' (vector of 2 'long long' values) to 'bool' for 1st argument
    really_inline simd8<bool>(bool _value) : base8<bool>(splat(_value)) {}
                  ^
./simdjson.cpp:2573:35: error: member initializer 'base8' does not name a non-static
      data member or base class
    really_inline simd8<bool>() : base8() {}
                                  ^~~~~~~
./simdjson.cpp:2576:46: error: type 'base8<bool>' is not a direct or virtual base of
      'simdjson::haswell::simd::simd8<bool>'
    really_inline simd8<bool>(bool _value) : base8<bool>(splat(_value)) {}
                                             ^~~~~~~~~~~
./simdjson.cpp:2578:51: error: use of undeclared identifier '_mm256_movemask_epi8'; did
      you mean '_mm_movemask_epi8'?
    really_inline int to_bitmask() const { return _mm256_movemask_epi8(*this); }        
                                                  ^~~~~~~~~~~~~~~~~~~~
                                                  _mm_movemask_epi8
C:\Program Files\LLVM\lib\clang\10.0.0\include\emmintrin.h:4399:1: note: 
      '_mm_movemask_epi8' declared here
_mm_movemask_epi8(__m128i __a)
^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:2578:72: error: no viable conversion from 'const
      simdjson::haswell::simd::simd8<bool>' to '__m128i'
      (vector of 2 'long long' values)
    really_inline int to_bitmask() const { return _mm256_movemask_epi8(*this); }        
                                                                       ^~~~~
C:\Program Files\LLVM\lib\clang\10.0.0\include\emmintrin.h:4399:27: note: passing       
      argument to parameter '__a' here
_mm_movemask_epi8(__m128i __a)
                          ^
In file included from .\amalgamate_demo.cpp:5:
./simdjson.cpp:2579:46: error: use of undeclared identifier '_mm256_testz_si256'        
    really_inline bool any() const { return !_mm256_testz_si256(*this, *this); }        
                                             ^
./simdjson.cpp:2580:64: error: invalid operands to binary expression ('const
      simdjson::haswell::simd::simd8<bool>' and 'bool')
    really_inline simd8<bool> operator~() const { return *this ^ true; }
                                                         ~~~~~ ^ ~~~~
./simdjson.cpp:2604:39: error: unknown type name '__m256i'
    really_inline base8_numeric(const __m256i _value) : base8<T>(_value) {}
                                      ^
./simdjson.cpp:2693:31: error: unknown type name '__m256i'
    really_inline simd8(const __m256i _value) : base8_numeric<int8_t>(_value) {}        
                              ^
./simdjson.cpp:2692:29: error: type 'base8_numeric<int8_t>' (aka 'base8_numeric<signed  
      char>') is not a direct or virtual base of
      'simdjson::haswell::simd::simd8<int8_t>'
    really_inline simd8() : base8_numeric<int8_t>() {}
                            ^~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping
```

**Comment by pps83** [comment]
You need https://github.com/simdjson/simdjson/pull/804 to get rid of deprecated warnings.
And you need `/arch:AVX2` to be able to compile it with clang

**Comment by pps83** [comment]
I get a clean build with clang

**Comment by lemire** [comment]
> I get a clean build with clang

The goal is to get a clean build with clang 10 without the AVX2 compiler flag.

**Comment by lemire** [comment]
> This isn't part of this PR, but clang will not compile simdjson without this flag.

It will with my PR. See my comment above. If you use the AVX2, you kill runtime dispatch. It will work for sure but that breaks one of our key features.

**Comment by pps83** [comment]
> > I get a clean build with clang
> 
> The goal is to get a clean build with clang 10 without the AVX2 compiler flag.

This PR is needed anyways to get it to compile. AVX2 flag - is another issue

File: src/haswell/intrinsics.h (hunk 1 above)
Comment (lemire) [reply src/haswell/intrinsics.h:8]: Let me compile this file 
```
#include <intrin.h>

int main() {
    
}
```

and track the headers that get included... (please use clang 10)

```
. C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\intrin.h
.. C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\x86intrin.h
... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\ia32intrin.h
... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\immintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\mmintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\xmmintrin.h
..... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\mm_malloc.h
...... C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18362.0\\ucrt\\stdlib.h 
....... C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18362.0\\ucrt\\corecrt.h
........ C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\include\\vcruntime.h
......... C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\include\\sal.h
.......... C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\include\\concurrencysal.h
......... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\vadefs.h
.......... C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\include\\vadefs.h
....... C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18362.0\\ucrt\\corecrt_malloc.h
....... C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18362.0\\ucrt\\corecrt_search.h
........ C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\stddef.h
......... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include/__stddef_max_align_t.h   
....... C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18362.0\\ucrt\\corecrt_wstdlib.h
....... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\limits.h
........ C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\include\\limits.h
...... C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18362.0\\ucrt\\malloc.h
..... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\emmintrin.h
...... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\xmmintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\pmmintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\tmmintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\smmintrin.h
..... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\popcntintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\wmmintrin.h
..... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\__wmmintrin_aes.h
..... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\__wmmintrin_pclmul.h        
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\avxintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\avx2intrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\f16cintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\bmiintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\bmi2intrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\lzcntintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\fmaintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\fxsrintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\xsaveintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\xsaveoptintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\adxintrin.h
.... C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\include\\invpcidintrin.h
.. C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\include\\setjmp.h
````

If you look at the intrin.h file in question, it has...

```
/* First include the standard intrinsics. */
#if defined(__i386__) || defined(__x86_64__)
#include <x86intrin.h>
#endif
```


In turn this header has...

```

#include <ia32intrin.h>

#include <immintrin.h>
```

In turn, the immintrin.h file is long but it looks like this...

```

#ifndef __IMMINTRIN_H
#define __IMMINTRIN_H

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__MMX__)
#include <mmintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__SSE__)
#include <xmmintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__SSE2__)
#include <emmintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__SSE3__)
#include <pmmintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__SSSE3__)
#include <tmmintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || \
    (defined(__SSE4_2__) || defined(__SSE4_1__))
#include <smmintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || \
    (defined(__AES__) || defined(__PCLMUL__))
#include <wmmintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__CLFLUSHOPT__)
#include <clflushoptintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__CLWB__)
#include <clwbintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__AVX__)
#include <avxintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__AVX2__)
#include <avx2intrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__F16C__)
#include <f16cintrin.h>
#endif

#if !defined(_MSC_VER) || __has_feature(modules) || defined(__VPCLMULQDQ__)
#include <vpclmulqdqintrin.h>
#endif
 and so forth
```

So you see that if you compile with AVX2 (which enables most other things in this file), you will get the other includes for free...

Comment (lemire) [reply src/haswell/intrinsics.h:8]: Now let us say that I compile this...

```
//#include <intrin.h>
 #include <bmiintrin.h>
 #include <lzcntintrin.h>
 #include <immintrin.h>
 #include <wmmintrin.h>
int main() {

}
```

Then I get...
```
In file included from .\test.cpp:2:
C:\Program Files\LLVM\lib\clang\10.0.0\include\bmiintrin.h:11:2: error: "Never use      
      <bmiintrin.h> directly; include <x86intrin.h> instead."
#error "Never use <bmiintrin.h> directly; include <x86intrin.h> instead."
 ^
In file included from .\test.cpp:3:
C:\Program Files\LLVM\lib\clang\10.0.0\include\lzcntintrin.h:11:2: error: "Never use    
      <lzcntintrin.h> directly; include <x86intrin.h> instead."
#error "Never use <lzcntintrin.h> directly; include <x86intrin.h> instead."
 ^
2 errors generated.
```


So you see, it wants us to go through <x86intrin.h>.

**Comment by lemire** [comment]
> This PR is needed anyways to get it to compile.

Does it compile for you without the AVX2 flag?

**Comment by lemire** [comment]
The issue we are trying to solve, or that I am trying to solve is this:

https://github.com/simdjson/simdjson/issues/763

**Comment by lemire** [comment]
Let me quote the documentation:


> The simdjson library automatically sets header flags for each implementation as it compiles; there is no need to set architecture-specific flags yourself (e.g., -mavx2, /AVX2 or -march=haswell), and it may even break runtime dispatch and your binaries will fail to run on older processors.

https://github.com/simdjson/simdjson/blob/master/doc/implementation-selection.md

That's a key difficulty.

**Comment by jkeiser** [comment]
@pps83 on my phone, but have a look at the TARGET_HASWELL and TARGET_WESTMERE macros (portability.h I think). That's where we are trying to add the compiler flags, so that implementations can each use their own instruction sets.

File: src/haswell/intrinsics.h [hunk 3]
```diff
@@ -4,7 +4,14 @@
...
+#ifdef __clang__
+#include <bmiintrin.h>
```
Comment (lemire) [inline src/haswell/intrinsics.h:10]: Though, admitted, we probably crash and burn under ARM with Visual Studio, this is of course not going to work... e.g., if you try to use Visual Studio to compile for android with clang, this will blow up.

**Comment by lemire** [comment]
@jkeiser 

> have a look at the TARGET_HASWELL and TARGET_WESTMERE macros (portability.h I think). That's where we are trying to add the compiler flags, so that implementations can each use their own instruction sets.

And it works when compiling clang under Visual Studio except that...

1. If _MSC_VER is defined, then simdjson assumes that we have Visual Studio and does not use the targets.

2. clang does something weird where, for example, the AVX2 intrinsics are only available if either _MSC_VER is undefined or if __AV2__ is defined.  That's right there in the headers. It is not justified nor documented anywhere. My guess for why that is... is that under Visual Studio, if you use an AVX2 intrinsic, even without the arch:AVX2, it is going to compile and link... but blow up only at runtime. This makes it remarkably easy, under Visual Studio, to support runtime dispatch. The same code under clang would normally fail at compile time (failure to inline)... This forces simdjson to use targets and stuff. But,  so the LLVM guys decided, I guess, that by guarding the includes, the programmer would get a warning at compile time about the function being undefined. Probably that telling the programmer to use attributes and targets was too much, because they want the same code to compile without change under Visual Studio and clang. So the programmer would then use arch:AVX2 and everything would be well again like @pps83  did. Of course, though you build and link... and everything looks fine... it is at runtime that it blows up because you no longer have working runtime dispatch.

**Comment by jkeiser** [comment]
It also bugs me that Visual Studio won't get to take advantage of the increased number of registers in different architectures.

Is our only choice to have multiple top level .cpp files (one per architecture)?

**Comment by lemire** [comment]
> Is our only choice to have multiple top level .cpp files (one per architecture)?

I think that a decision was taken early on to make it so that people could compile this as a single-header blob. This makes it so that you don't have to use CMake or any specific build system, IDE. You can just drop two files in your project and be done with it.

I think it is an underrated feature. It is one of the few things in simdjson that I will fight for (and @pps83 testified how great he felt it was).

As to your point, the programmer is building his or her software with some target systems in mind. They make the choice of limiting their app. Nothing prevents a programmer from throwing arch:AVX2 in there... the key point is that they will then be responsible for the runtime crashes.

Last I benchmarked simdjson on Visual Studio, the performance was less than under Linux... but the gap was not large. If it had been, I would have made a fuss about it, and people using simdjson under Windows would have raised issues. Where does the difference comes from? Some of it came from the fact that Visual Studio won't let us use computed GOTOs. From my recollection, the stage 1 was pretty much on par (Visual Studio vs clang). I think stage 2 was slower, but, again, I think a good chunk came from the lack of computed GOTOs. Of course, these are rough numbers, achieved by dual booting the same machine.

**Comment by jkeiser** [comment]
@lemire I could imagine amalgamating 5 files instead of 2 (simdjson.h, simdjson-core.cpp, simdjson-westmere.cpp, simdjson-haswell.cpp, simdjson-arm64.cpp).

I'm embarrassed I never checked this, but Windows is notably slower than Linux on my machine/OS (it actually brings it down roughly to the speed of RapidJSON). When I run under WSL, I get 2.6GB/s, but the Windows Release version is 1.0GB/s. It's a separate issue from this, though. Compiling with /arch:AVX2 only bought me a 10% improvement. I'll file an issue.

**Comment by lemire** [comment]
> And you need /arch:AVX2 to be able to compile it with clang

The reason you need arch:AVX2 is that under clang, either __AVX2__ must be defined or _MSC_VER must be undefined for the AVX2 intrinsics be included.

The next issue is that if _MSC_VER is defined, simdjson assume that we are under Visual Studio and so it does not use the TARGET_HASWELL macros, so even if you can get to the intrinsics, clang will refuse to compile them (even if the function was defined) because it is not allowed to emit AVX2 instructions.

So what I do in my PR (that I think I retired now) is to define __AVX2__, thus fooling clang into thinking that it has AVX2, and so I get the function definitions from the headers. Then, I undefine _MSC_VER so that simdjson will issue the TARGET_HASWELL macros.

So my PR solved the problem, but it is still too fragile because if some had "#include <intrin.h>" somewhere in their code before they include simdjson, we are dead again.

Finally, another issue is that we do not have CI for clang under Windows so supporting it is not practical. Now, if we did manage to get CI working for it, that would be something else.

**Comment by lemire** [comment]
> I could imagine amalgamating 5 files instead of 2 (simdjson.h, simdjson-core.cpp, simdjson-westmere.cpp, simdjson-haswell.cpp, simdjson-arm64.cpp). That's just about as easy to drag as 2.

We could do that in the future... but it is maybe harder for users to organize the build afterward. It is really hard to beat the ease-of-use of big blobs to be compiled as big blobs without worry.



> When I run under WSL, I get 2.6GB/s, but the Windows Release version is 1.0GB/s. It's a separate issue from this, though. Compiling with /arch:AVX2 only bought me a 10% improvement. I'll file an issue.

That's a regression because it did not used to be this way. Of course, I have not been monitoring speeds under Windows.

**Comment by jkeiser** [comment]
Yeah, another reason getting checkperf for non-linux platforms will help.

Also a reason having a historical performance chart checking things asynchronously will help!

**Comment by lemire** [comment]
> Also a reason having a historical performance chart checking things asynchronously will help!

I guess that the idea would be to run Windows "bare metal" in Azure in such a way that we can specify the hardware... and then run the benchmarks periodically...?

You think that's doable?

**Comment by pps83** [comment]
Usually, it's should be possible to set arch with pragmas for some code ranges. Just need to find which ones are needed and it could be fixed.

**Comment by lemire** [comment]
If you could find that, it would be fantastic. Can you also look at the performance issue that @jkeiser is working on... I'll ping you there.

**Comment by jkeiser** [comment]
> I guess that the idea would be to run Windows "bare metal" in Azure in such a way that we can specify the hardware... and then run the benchmarks periodically...?
> 
> You think that's doable?

I think it's doable, but don't know how much noise it will have. I do imagine CI runs uploading their results.

But even more, I imagine being able to run a script or something that will do something like `git bisect` and run performance tests on whatever machine you want, running different combinations and different commits, and uploading the perf results until you decide you want to use your machine again and hit ctrl+C. That way we could set up our own machines with no noisy neighbors and run every so often. It doesn't have to be regular to make a difference; just means you find out about platform regressions later, which is much better than "not at all." And I suspect we'd run it on demand when we do things we are worried will affect platform performance.

**Comment by lemire** [comment]
@jkeiser Could this be done using CMake, do you think? (This is not a feature request from me to you.)

**Comment by lemire** [comment]
@jkeiser (Rather, I am thinking about *how* to best do it.)

**Comment by lemire** [comment]
cc @yoannlr

**Comment by pps83** [comment]
> If you could find that, it would be fantastic. Can you also look at the performance issue that @jkeiser is working on... I'll ping you there.

`#pragma clang attribute push (__attribute__((target("avx2"))), apply_to=function)`

[see example for gcc and clang](https://godbolt.org/z/9ca69B)

**Comment by jkeiser** [comment]
> @jkeiser Could this be done using CMake, do you think?

I'll respond in #717 :)

**Comment by lemire** [comment]
@pps83 Yes. We use `#pragma clang attribute push (__attribute__((target("avx2"))), apply_to=function)` already in simdjson. We are missing the equivalent in Visual Studio.

**Comment by jkeiser** [comment]
@lemire he makes a good point there though--maybe that's our way forward for clang-on-VS? It might even be the right recommendation for people who want performance on Windows.

**Comment by lemire** [comment]
@jkeiser  Sure. But I have explained the problem. Let me restate it as cleanly as a I can.

If you use clang under Windows, the _MSC_VER macro is set and when you include the intrinsic header, then clang will not import the definition/declaration of the intrinsics. And then you are dead.

If you can control how the intrinsic header is imported, you are fine. (This PR here is not the way to do it. You need either to set __AVX2__ and friends before including the header or undefining _MSC_VER, and then you need simdjson to ignore the _MSC_VER macro like I did in my now-closed PR). So if you are building a library and you control how it is done... you are good. But the minute someone wants to integrate directly the simdjson code into their project, they are handed back the control and hell may follow.

Now, it is possible to detect that the intrinsic header was imported upstream... and warn the programmer... but it feels fragile to me.

I would love for us to support clang under Windows. I just don't want to support something that breaks when you look at it the wrong way.

**Comment by lemire** [comment]
Ok. I am going to merge this PR but immediately reopen the issue it claims to be fixing because I don't think it does fix it. But I think that this PR is a step forward.

**Comment by jkeiser** [comment]
@lemire yep. I think though, that if we add the constraint that you aren't allowed to `#include "simdjson.cpp"` (which most people won't naturally think to do anyway), we can make it work. As long as clang a.cpp b.cpp c.cpp lets each of them import the headers separately, we can probably make it all go without forcing the user to use complicated compilation methods. The thing that would be nightmarish is if we had to tell people to run clang 4 times with 4 different sets of flags.

**Comment by lemire** [comment]
For people reading this: The issue was finally resolved. By combining @pps83's strategy with more hacking... we now have something that works well...
