### PR TITLE
fix segfault in numberparsing #1273

### LINKED ISSUE #1273: generic/numberparsing.h compute_float_64() invoked with out of range power
The CI fuzzer found a crash (segfault, out of bound read), which I reduced to compute_float_64() being invoked with power outside of the stated legal range, eventually leading to the out of bounds read.

The following reproduces the problem (the asserts will trigger):
```diff
diff --git a/include/simdjson/generic/numberparsing.h b/include/simdjson/generic/numberparsing.h
index 934e57e3..9490f1c1 100644
--- a/include/simdjson/generic/numberparsing.h
+++ b/include/simdjson/generic/numberparsing.h
@@ -42,6 +42,8 @@ simdjson_really_inline double to_double(uint64_t mantissa, uint64_t real_exponen
 // We assume that power is in the [smallest_power,
 // largest_power] interval: the caller is responsible for this check.
 simdjson_really_inline bool compute_float_64(int64_t power, uint64_t i, bool negative, double &d) {
+  assert(power>=simdjson::internal::smallest_power);
+  assert(power<=simdjson::internal::largest_power);
   // we start with a fast path
   // It was described in
   // Clinger WD. How to read floating point numbers accurately.
diff --git a/tests/ondemand/ondemand_basictests.cpp b/tests/ondemand/ondemand_basictests.cpp
index 58766088..5e669f33 100644
--- a/tests/ondemand/ondemand_basictests.cpp
+++ b/tests/ondemand/ondemand_basictests.cpp
@@ -326,8 +326,19 @@ namespace number_tests {
     printf("Powers of 10 can be parsed.\n");
     return true;
   }
+
+  bool weird_case() {
+    padded_string bad(std::string_view("0.0300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000122978293824"));
+    simdjson::builtin::ondemand::parser parser;
+    simdjson_unused auto blah=parser.iterate(bad);
+    double x;
+    simdjson_unused auto blah2=blah.get(x);
+    return true;
+  }
+
   bool run() {
-    return small_integers() &&
+    return weird_case() &&
+           small_integers() &&
            powers_of_two() &&
            powers_of_ten();
   }
```

The proposed fix solves the problem:
```diff
diff --git a/include/simdjson/generic/numberparsing.h b/include/simdjson/generic/numberparsing.h
index 9490f1c1..098a90b0 100644
--- a/include/simdjson/generic/numberparsing.h
+++ b/include/simdjson/generic/numberparsing.h
@@ -736,11 +736,12 @@ simdjson_unused simdjson_really_inline simdjson_result<double> parse_double(cons
     if (p-start_exp_digits == 0 || p-start_exp_digits > 19) { return NUMBER_ERROR; }
 
     exponent += exp_neg ? 0-exp : exp;
-    overflow = overflow || exponent < simdjson::internal::smallest_power || exponent > simdjson::internal::largest_power;
   }
 
   if (jsoncharutils::is_not_structural_or_whitespace(*p)) { return NUMBER_ERROR; }
 
+  overflow = overflow || exponent < simdjson::internal::smallest_power || exponent > simdjson::internal::largest_power;
+
   //
   // Assemble (or slow-parse) the float
   //
```

### PR DESCRIPTION
**Pull request by pauldreik**
Closes #1273

### CODE REVIEW

**Comment by pauldreik** [comment]
I am pretty sure I understood how this bug triggered and that my fix is correct. Nevertheless it would need review. @jkeiser maybe?

**Comment by lemire** [comment]
Let me have a look!

File: include/simdjson/generic/numberparsing.h [hunk 1]
```diff
@@ -734,11 +736,12 @@ simdjson_unused simdjson_really_inline simdjson_result<double> parse_double(cons
     if (p-start_exp_digits == 0 || p-start_exp_digits > 19) { return NUMBER_ERROR; }
 
     exponent += exp_neg ? 0-exp : exp;
-    overflow = overflow || exponent < simdjson::internal::smallest_power || exponent > simdjson::internal::largest_power;
   }
 
   if (jsoncharutils::is_not_structural_or_whitespace(*p)) { return NUMBER_ERROR; }
 
+  overflow = overflow || exponent < simdjson::internal::smallest_power || exponent > simdjson::internal::largest_power;
```
Comment (lemire) [inline include/simdjson/generic/numberparsing.h:743]: We have an identical line just above... (line 737). I think it would be better to move it, around near where you have it now...

```C++
    overflow = overflow || exponent < simdjson::internal::smallest_power || exponent > simdjson::internal::largest_power;
```

I think @jkeiser was assuming that without an explicit exponent, you could never exceed the valid range... but it is incorrect.

File: include/simdjson/generic/numberparsing.h [hunk 2]
```diff
@@ -42,6 +42,8 @@ simdjson_really_inline double to_double(uint64_t mantissa, uint64_t real_exponen
 // We assume that power is in the [smallest_power,
 // largest_power] interval: the caller is responsible for this check.
 simdjson_really_inline bool compute_float_64(int64_t power, uint64_t i, bool negative, double &d) {
+  assert(power>=simdjson::internal::smallest_power);
```
Comment (lemire) [inline include/simdjson/generic/numberparsing.h:45]: I would be tempted to remove these asserts... this is not a function that is callable by our users. It is only ever called by us, and we should (it is our job) track down the calls and ensure that we guard them appropriately.

But it is just a mild preference. Note that some users compile in release mode with asserts (as part of generic policies). Thankfully, they won't do that with On Demand...  but they might with DOM. (I hope not.)

**Comment by lemire** [comment]
@pauldreik I think we need to understand the bug first. I am sure you do, but I cannot figure it out from your changes.

So you are saying that `compute_float_64` is called with an out-of-bound power.

As far as I can tell, this function is called exactly just twice... once on line 475...

```C++
  if (simdjson_unlikely(exponent < simdjson::internal::smallest_power) || (exponent > simdjson::internal::largest_power)) {
    if((exponent < simdjson::internal::smallest_power) || (i == 0)) {
      WRITE_DOUBLE(0, src, writer);
      return SUCCESS;
    } else { // (exponent > largest_power) and (i != 0)
      // We have, for sure, an infinite value and simdjson refuses to parse infinite values.
      return INVALID_NUMBER(src);
    }
  }
  double d;
  if (!compute_float_64(exponent, i, negative, d)) {
```

So that's clearly a "guarded call". No issue there.

The other call, and the one you are fixing, is the one that only appears partially guarded.

You added a second "overflow" computation, but I think we could just move it, see my comments.

**Comment by lemire** [comment]
(Note that, as is obvious, I did figure out the bug, I am just saying I could not figure it out from the diff alone.)

File: include/simdjson/generic/numberparsing.h (hunk 1 above)
Comment (pauldreik) [reply include/simdjson/generic/numberparsing.h:743]: I don't understand what you mean here, I moved this particular line from 737 to 743?

Comment (lemire) [reply include/simdjson/generic/numberparsing.h:743]: If you did do so, then ignore my comment.

File: include/simdjson/generic/numberparsing.h (hunk 2 above)
Comment (pauldreik) [reply include/simdjson/generic/numberparsing.h:45]: I like asserts, but I agree the risk of having people having them active is not what we want. Instead, we have fuzz testing, unit tests and sanitizers. I will remove them.

**Review by lemire — APPROVED** [review]
This is good.

It looks like @pauldreik found a real bug with the On Demand API that needs fixing. Excellent. (And he fixed it.)

**Comment by pauldreik** [comment]
I'm sorry, but I don't understand what you mean? parse_double() calls compute_float_64(). It makes sense parse_double had to be fixed, so it did not violate the assumptions of compute_float_64(). I *moved* the check a few lines, not duplicated it. 

Then there is write_float() which I did not touch that also calls compute_float_64(). It has it's own checks already.

**Comment by pauldreik** [comment]
Merging, with the chance that there is a redundant check I did not understand.

**Comment by pauldreik** [comment]
Since we just made a release with this new functionality and this is a potential security issue, should we make a patch release?

**Comment by pauldreik** [comment]
Oh, I forgot to submit the removal of asserts. Will fix it.

**Comment by lemire** [comment]
+1
